### ISSUE TITLE
HTML Encode the Secrets values

### ISSUE THREAD

**Issue by LanceMcCarthy** [MrYossu/Pixata.Utilities#3]
I have confirmed your latest commit to master builds successfully in the workflow over in my fork. See the result just a few moments ago here https://github.com/LanceMcCarthy/Pixata.Utilities/runs/1729177449?check_suite_focus=true 

Please follow the instructions I sent in my support case reply about resetting the secrets. 

When it comes to your password, please run it through an HtmlEncoding utility to escape any special characters.

Here's how to use it:

1. Open Powershell
2. Run the following command (replace my§uper&P@§§word with your real password)

```
Add-Type -AssemblyName System.Web
[System.Web.HttpUtility]::HtmlEncode('my§uper&P@§§word')
```

![image](https://user-images.githubusercontent.com/3520532/105066446-d0add680-5a4c-11eb-9dc7-fa7d0e154c11.png)

**Comment by MrYossu** [comment]
Hello,

Thanks for this, however I've done both of these steps before. I mentioned in my reply of Jan 14th that I had tried encoding my password, but as it only contains digits, letters (upper and lower) and a hyphen, the encoded version was exactly the same as the plain.

I have also deleted and recreated the secrets a couple of times, but it didn't help.

What puzzles me is why it thinks the user name is empty. Even if I had the wrong credentials in there, it should pick them up and say they were wrong, not empty. An empty user name sounds like it's just not finding the secret at all. However, as you can see my workflow, and I posted a screenshot of the secrets, where you can see the names, it should be picking them up.

I wonder if there's something else going on here that I'm missing. Are you sure that this message is due to not being able to fid the secrets when trying to restore the package from your server?  I'm not saying you're wrong, I really know very little about this, but it just doesn't seem to make sense.

Any thoughts? Thanks again.

**Comment by LanceMcCarthy** [comment]
I just saw your Secrets screenshot... that is not the correct Secrets page. That is why you are not having any values when you run the workflows.

![image](https://user-images.githubusercontent.com/3520532/105068435-efad6800-5a4e-11eb-98b5-e30a03530e50.png)

**Comment by LanceMcCarthy** [comment]
congrats!
![image](https://user-images.githubusercontent.com/3520532/105069759-6008b900-5a50-11eb-98e5-c05fd65e9c36.png)

**Comment by MrYossu** [comment]
You're amazing! Thanks so much!

I tried creating a release branch, which all worked fine, but I can't see my packages in nuget. Is there something else I need to do to get them to show there? I started out [following this article](https://dzone.com/articles/build-publish-and-deploy-nuget-package-using-githu), which is basically what you helped me do, but noting showing in nuget.

Thanks again

**Comment by MrYossu** [comment]
Ah, seems like I haven't got this right yet. I created a release branch, but the release.yml workflow hasn't been run. Is there a way to get it to run? I think I'm missing some important point here.

**Comment by LanceMcCarthy** [comment]
you need a branch named 'release', then you need to push a commit to the release branch to trigger the build. The most common way to trigger such a build is to do the following:

Add a commit to master branch, so that master is ahead of release, then merge master into release. That will cause a merge commit and trigger the release branch's workflow


In the meantime, I would greatly appreciate if you could close the private Support Ticket (it goes a long way when you mark it closed yourself, because it is an indication we were able to help :)

**Comment by LanceMcCarthy** [comment]
I do not see any release branch in this repo, did you only make the brnahc locally and forget to push it to Github?

![image](https://user-images.githubusercontent.com/3520532/105072930-5d0fc780-5a54-11eb-9bc6-b57f104b12cf.png)

**Comment by LanceMcCarthy** [comment]
success!

![image](https://user-images.githubusercontent.com/3520532/105074029-dc51cb00-5a55-11eb-9b2f-78cc3ea09325.png)

> Here's a more in depth article on how to use GitHub actions for a complete workflow https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

**Comment by MrYossu** [comment]
OK, so I'm confused (nothing new!). Thanks for the link, but it's the source control part of tis that I'm not undertanding.

I created a new branch called release in VS, but then had problems working out how to use it. I could switch branches, but they both look the same (because they were). I then tried adding some meta info to the project files for the two projects that will end up as Nuget packages. This was as much to have something to merge into the release branch.

However, I could not see any way to merge the master into the release. I committed and pushed all changes, but the project files in the release branch stayed at the old versions.

I then tried creating a release branch from GitHub itself, which worked, and kicked off the build/publish. Hurray, I now have both projects published on Nuget ([Blazor](https://www.nuget.org/packages/Pixata.Blazor/) and [Extensions](https://www.nuget.org/packages/Pixata.Extensions/)). However, the two project files in the release branch in GitHub show the changes, but the local ones don't. It looks like VS is ignoring the release branch in GitHub and GitHub is ignoring the release branch in VS.

So I'm obviously missing some part of the source control work flow here. I don't know if all that explanation made sense, but do you have any idea what I've done wrong? I thought I would just be able to switch to the release branch, merge in the changes from the master, push them and have the workflow build and publish the packages.

Thanks again.

**Comment by LanceMcCarthy** [comment]
I never use Git inside Visual Studio. If you're going to stay on GitHub, I highly recommend using GitHub for Desktop app instead. It will automatically handle the upstream stuff when you sync and it will be really clear about what it going to happen (it prefetches, etc).

Get it here https://desktop.github.com/

**Comment by MrYossu** [comment]
Thanks, having mucked the whole thing up by moving the project folder, I started again by using Git Desktop to clone the repo from GitHub. Now I can do my dev work in VS on the master branch, then when I'm ready to release, use Git Desktop to merge the master into the release, and the build/publish works.

Don't know why this was so complicated in VS, dead easy in Git Desktop 😀

One more question if you don't mind. If you look at the [Nuget page](https://www.nuget.org/packages/Pixata.Blazor/), there isn't any info, such as the project URL, package description, etc. I added a Pixata.Blazor.nuspec file next to the .csproj file...

```
<?xml version="1.0" encoding="utf-8" ?>
<package>
  <metadata>
    <id>Pixata.Blazor</id>
    <version>1.0.0</version>
    <title>Pixata.Blazor</title>
    <authors>Pixata Ltd</authors>
    <owners>Avrohom Yisroel Silver</owners>
    <projectUrl>https://www.pixata.co.uk/</projectUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>A set of Blazor components that may be useful</description>
    <releaseNotes>Initial 1.0.0 release</releaseNotes>
    <copyright>Copyright 2021 Pixata Ltd</copyright>
    <tags>Blazor</tags>
    <dependencies>
      <dependency id="Microsoft.AspNetCore.Components.Web" version="5.0.0" />
      <dependency id="Microsoft.AspNetCore.WebUtilities" version="2.2.0" />
      <dependency id="PeterLeslieMorris.Blazor.FluentValidation" version="1.5.0" />
      <dependency id="PeterLeslieMorris.Blazor.Validation" version="1.5.0" />
      <dependency id="Telerik.UI.for.Blazor" version="2.20.0" />
	</dependencies>
    <summary>A set of Blazor components that may be useful. There are currently components for laying out forms, and some useful containers, such as confirm and inform pseudo-dialogs (no JavaScript!), a busy (loading...) indicator and so on.</summary>
  </metadata>
</package>
```

...and a similar one for the other package, but even after republishing, the info doesn't show up on the Nuget page.

Any ideas? Thanks again.

**Comment by LanceMcCarthy** [comment]
Unfortunately, I'm not of much assistance here. I've never used a nuspec to include package information, I just use the csproj section for that purpose. 

Here's an example (my only production package) https://github.com/LanceMcCarthy/CommonHelpers/blob/9922ef7bd554d80427f49024d9ef442d23c05f2d/CommonHelpers/CommonHelpers/CommonHelpers.csproj#L3-L24 

For more help with nuspec, try Microsoft Q&A, a new system that replaced MSDN and is actively monitored https://docs.microsoft.com/en-us/answers/products/dotnet

**Comment by MrYossu** [comment]
Thanks, took some fighting with VS and GitHub, but it all seems to be working now. 

Thanks again for all the help 👍

**Comment by LanceMcCarthy** [comment]
That's amazing news. I know it is frustrating using YAML for devops at first (especially when you're used to suberb experience with .NET development inside Visual Studio :D).

To wrap this up I'm going to close this thread (you should remove me from collaborators). If you have any trouble in the future, don't hesitate to open a new Support Ticket, Marin is a Blazor wizard.
