### ISSUE TITLE
User signin and permission usage

### ISSUE THREAD

**Issue by Xyolyp** [MrYossu/Pixata.Utilities#6]
I found this on my endevor of getting data from the google fitness api. I would be able to modify your code to work with the fitness api if it would work with users authorization via OAuth. Google determines the fitness data to be protection worthy and therefor no application has access without using user authorization.
I'd appreciate if you found a way to implement the OAuth flow in a blazor server compatible manner.

**Comment by MrYossu** [comment]
@Xyolyp The code I have here wouldn't work with OAuth, as that requires an interaction between the user and the site. The Google Drive code is intended for use from a server, without any user interaction. That's why it uses a service account, which is designed for that kind of situation.

If you want the best information on accessing Google from your code, I suggest you look at [Linda Lawton's site](https://daimto.com/). She's an expert on the subject, and has many tutorials on how to do pretty much everything you need. I seem to remember that she covers OAuth quite well, although I stopped looking at that when she pointed out to me that I needed a service account.

Hope that helps.
